# Generated by Django 5.2.7 on 2025-10-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.TextField(default='No description available'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(default='http://example.com/default_video.mp4'),
            preserve_default=False,
        ),
    ]
